# Generated by Django 4.1.7 on 2023-04-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test_date',
            field=models.DateTimeField(null=True),
        ),
    ]
