# Generated by Django 4.1.7 on 2023-04-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_task_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test_date',
        ),
    ]
